import type { Person, Relationship, ProjectMeta, LayoutConfig } from "@/types/domain";

const persons: Person[] = [
  {
    id: "p1",
    firstName: "Giovanni",
    lastName: "Rossi",
    gender: "male",
    birthDate: "1930",
    birthPlace: "Roma, Italia",
    deathDate: "2005",
    deathPlace: "Roma, Italia",
    photo: null,
    notes: "Nonno paterno",
    customFields: {},
  },
  {
    id: "p2",
    firstName: "Maria",
    lastName: "Bianchi",
    gender: "female",
    birthDate: "1932",
    birthPlace: "Napoli, Italia",
    deathDate: "2018",
    deathPlace: "Roma, Italia",
    photo: null,
    notes: "Nonna paterna",
    customFields: {},
  },
  {
    id: "p3",
    firstName: "Luigi",
    lastName: "Verdi",
    gender: "male",
    birthDate: "1928",
    birthPlace: "Milano, Italia",
    deathDate: "2000",
    deathPlace: "Milano, Italia",
    photo: null,
    notes: "Nonno materno",
    customFields: {},
  },
  {
    id: "p4",
    firstName: "Anna",
    lastName: "Ferrari",
    gender: "female",
    birthDate: "1935",
    birthPlace: "Firenze, Italia",
    deathDate: null,
    deathPlace: null,
    photo: null,
    notes: "Nonna materna",
    customFields: {},
  },
  {
    id: "p5",
    firstName: "Marco",
    lastName: "Rossi",
    gender: "male",
    birthDate: "1960-05-12",
    birthPlace: "Roma, Italia",
    deathDate: null,
    deathPlace: null,
    photo: null,
    notes: "",
    customFields: {},
  },
  {
    id: "p6",
    firstName: "Laura",
    lastName: "Verdi",
    gender: "female",
    birthDate: "1963-08-22",
    birthPlace: "Milano, Italia",
    deathDate: null,
    deathPlace: null,
    photo: null,
    notes: "",
    customFields: {},
  },
  {
    id: "p7",
    firstName: "Alessandro",
    lastName: "Rossi",
    gender: "male",
    birthDate: "1990-03-15",
    birthPlace: "Roma, Italia",
    deathDate: null,
    deathPlace: null,
    photo: null,
    notes: "",
    customFields: {},
  },
  {
    id: "p8",
    firstName: "Sofia",
    lastName: "Rossi",
    gender: "female",
    birthDate: "1993-11-02",
    birthPlace: "Roma, Italia",
    deathDate: null,
    deathPlace: null,
    photo: null,
    notes: "",
    customFields: {},
  },
];

const relationships: Relationship[] = [
  { id: "r1", type: "partner", from: "p1", to: "p2", subtype: "married", startDate: "1955", endDate: null, location: null },
  { id: "r2", type: "partner", from: "p3", to: "p4", subtype: "married", startDate: "1958", endDate: null, location: null },
  { id: "r3", type: "parent-child", from: "p1", to: "p5", subtype: "biological", startDate: null, endDate: null, location: null },
  { id: "r4", type: "parent-child", from: "p2", to: "p5", subtype: "biological", startDate: null, endDate: null, location: null },
  { id: "r5", type: "parent-child", from: "p3", to: "p6", subtype: "biological", startDate: null, endDate: null, location: null },
  { id: "r6", type: "parent-child", from: "p4", to: "p6", subtype: "biological", startDate: null, endDate: null, location: null },
  { id: "r7", type: "partner", from: "p5", to: "p6", subtype: "married", startDate: "1988", endDate: null, location: null },
  { id: "r8", type: "parent-child", from: "p5", to: "p7", subtype: "biological", startDate: null, endDate: null, location: null },
  { id: "r9", type: "parent-child", from: "p6", to: "p7", subtype: "biological", startDate: null, endDate: null, location: null },
  { id: "r10", type: "parent-child", from: "p5", to: "p8", subtype: "biological", startDate: null, endDate: null, location: null },
  { id: "r11", type: "parent-child", from: "p6", to: "p8", subtype: "biological", startDate: null, endDate: null, location: null },
];

const meta: ProjectMeta = {
  name: "Famiglia Rossi",
  description: "Albero genealogico di esempio della famiglia Rossi",
  createdAt: "2026-02-11T10:00:00Z",
  updatedAt: "2026-02-11T10:00:00Z",
  author: "Demo",
  projectType: "familyTree",
};

const layout: LayoutConfig = {
  orientation: "vertical",
  rootPersonId: "p1",
  nodePositions: {},
};

export const demoProject = { persons, relationships, meta, layout };
